[package]
name = "interview"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
futures = "0.3"
libc = "0.2"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
kube = "1.1"
k8s-openapi = { version = "0.24", features = ["earliest"] }
